"""initial

Revision ID: 68a94dc598d3
Revises: 
Create Date: 2026-04-29 13:01:56.276017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a94dc598d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('certames',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('numero_edital', sa.String(), nullable=True),
    sa.Column('orgao', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'planejamento', 'em_andamento', 'concluido', 'cancelado', name='certamestatus'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'logistica', 'coordenador', name='userrole'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('importacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('certame_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('candidatos', 'locais', 'equipes', 'condicoes_especiais', 'cargos_periodos', name='importacaotipo'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'processando', 'concluido', 'erro', name='importacaostatus'), nullable=True),
    sa.Column('nome_arquivo', sa.String(), nullable=True),
    sa.Column('total_linhas', sa.Integer(), nullable=True),
    sa.Column('linhas_importadas', sa.Integer(), nullable=True),
    sa.Column('erros', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certame_id'], ['certames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('certame_id', sa.String(), nullable=False),
    sa.Column('coordenador_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('total_salas', sa.Integer(), nullable=True),
    sa.Column('capacidade_total', sa.Integer(), nullable=True),
    sa.Column('acessivel', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certame_id'], ['certames.id'], ),
    sa.ForeignKeyConstraint(['coordenador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('certame_id', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certame_id'], ['certames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('certame_id', sa.String(), nullable=False),
    sa.Column('periodo_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('total_inscritos', sa.Integer(), nullable=True),
    sa.Column('total_deferidos', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['certame_id'], ['certames.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('presenca', sa.Enum('pendente', 'presente', 'ausente', name='presencastatus'), nullable=True),
    sa.Column('observacao_coordenador', sa.Text(), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('acessivel', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cargo_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('inscricao', sa.String(), nullable=True),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('sala', sa.String(), nullable=True),
    sa.Column('condicoes_especiais', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('certame_id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('sala_id', sa.String(), nullable=True),
    sa.Column('candidato_id', sa.String(), nullable=True),
    sa.Column('registrado_por_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('candidato', 'fiscal', 'local', 'material', 'outros', name='ocorrenciatipo'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['certame_id'], ['certames.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocorrencias')
    op.drop_table('candidatos')
    op.drop_table('salas')
    op.drop_table('fiscais')
    op.drop_table('cargos')
    op.drop_table('periodos')
    op.drop_table('locais')
    op.drop_table('importacoes')
    op.drop_table('usuarios')
    op.drop_table('certames')
    op.drop_table('tenants')
    # ### end Alembic commands ###
